### ISSUE TITLE
PLYHandler shows 2 errors: TakeUntilIncluding and bytes.SubArray

### ISSUE THREAD

**Issue by carlabodyform3d** [3DBear/PlyImporter#1]
the fuction GetVerticesAndTriangles shows an error for the sentence: List<string> header = File.ReadLines(path).TakeUntilIncluding(x => x == "end_header").ToList();

Apparently don't recognize "TakeUntilIncluding".

Also the function: GetTriangles, shows  error two times for System.BitConverter.ToInt32(bytes.SubArray, it says there's no definition for SubArray.

**Comment by oniskanen** [comment]
@zeroregard, We're missing the `ArrayExtensions` and `EnumerableExtensions` from the repo. Do you want me to take over maintaining this?

**Comment by zeroregard** [comment]
Sorry for the late reply, please do go ahead if you have the time

**Comment by damonftl** [comment]
Hello, any chance these two extensions will be added to the repo? They don't seem to exist anywhere else and I'd love to try out this code. Thanks!

**Comment by oniskanen** [comment]
@damonftl @carlabodyform3d Apologies for the late response. I added the scripts now.
