### ISSUE TITLE
Running Script Abstract Class

### ISSUE THREAD

**Issue by albert239825** [3DBear/PlyImporter#3]
Hello, I'm trying to import an ASCII PLY file into a unity project but when I tried to apply the script onto the ply file in the hierarchy, it said that I can't apply abstract script classes. I'm a little confused with the usage directions and am wondering how exactly you are meant to use this importer. Sorry, I'm a little new to this Unity thing. Thanks!

![image](https://user-images.githubusercontent.com/43973217/105620649-237cea80-5dcd-11eb-86e7-8b3d65368d27.png)

**Comment by oniskanen** [comment]
The library only provides the routine for handling ply data. You’ll need to create the MonoBehaviour or editor script where you call the provided code.

An example:

```
public class Example : MonoBehaviour
{
    public void Start()
    {
        var result = PlyImporter.GetVerticesAndTriangles(”path/to/file.ply”);
    }
}
```

I’m on mobile and couldn’t verify the syntax, so the example might need tweaking.
